setup project
awesome-academy/HN_Pra19_Android_Anime_App pull request #1
Opened 2024-07-19 08:57 UTC by kienyk02

2024-07-19 09:53 UTC, HVgiang86 requested changes
- Không được xoá Pull Request description
- Các file luôn kết thúc bằng một dòng trống

2024-07-19 09:53 UTC, HVgiang86 commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
```suggestion
</androidx.constraintlayout.widget.ConstraintLayout>

```

2024-07-19 09:53 UTC, HVgiang86 commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
File content must end with a newline

2024-07-19 09:53 UTC, HVgiang86 commented on app/ktlint.gradle
> +}
```suggestion
}

```

2024-07-19 09:53 UTC, HVgiang86 commented on app/ktlint.gradle
> +}
File content must end with a newline

2024-07-19 09:53 UTC, HVgiang86 commented on app/src/main/res/values/strings.xml
>  </resources>
```suggestion
</resources>

```

2024-07-19 09:53 UTC, HVgiang86 commented on app/src/main/res/values/strings.xml
>  </resources>
File content must end with a newline

2024-07-19 10:05 UTC, huyenmi16 approved these changes
- [HN_Pra19_Android]_Le.Ngoc.Huyen (T2-W, T3-W, T4-W, T5-W, T6-A) nhóm 4 đồng ý với thay đổi của bạn

2024-07-19 10:07 UTC, nhat15072002 approved these changes

2024-07-22 01:33 UTC, gianghv-3456 requested changes
check my cmts

2024-07-22 01:33 UTC, gianghv-3456 commented on app/ktlint.gradle
> +}
```suggestion
}

```

2024-07-22 01:33 UTC, gianghv-3456 commented on app/ktlint.gradle
> +}
File content must end with a newline

2024-07-22 02:19 UTC, merged