initial api and queries
awesome-academy/HN_Pra19_Android_Anime_App pull request #4
Opened 2024-07-24 11:00 UTC by kienyk02

## Related Tickets
- [#Task 78177: Content](https://edu-redmine.sun-asterisk.vn/issues/78177)
## WHAT
- Cấu hình API.
- Tạo Queries.
- Fetch API tại Home screen.
## Evidence (Screenshot or Video)
![image](https://github.com/user-attachments/assets/cb39f431-c660-422e-ad5e-b776f9c198b7)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-07-24 11:07 UTC, huyenmi16 approved these changes

2024-07-25 01:21 UTC, nhat15072002 approved these changes

2024-07-26 04:10 UTC, gianghv-3456 requested changes
Pls check my cmts

2024-07-26 04:10 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/AnimeDataSource.kt
> +        fun getAnimePopular(limit: Int, page: Int, listener: OnResultListener<MutableList<Anime>>)
Data trả về từ Api là cố định, dùng List thay vì MutableList em nha, sau này khi cần sửa đổi ta sẽ chuyển sang mutable sau
```suggestion
        fun getAnimePopular(limit: Int, page: Int, listener: OnResultListener<List<Anime>>)
```

2024-07-26 04:10 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/AnimeDataSource.kt
> +        fun getAnimeFavorite(limit: Int, page: Int, listener: OnResultListener<MutableList<Anime>>)
```suggestion
        fun getAnimeFavorite(limit: Int, page: Int, listener: OnResultListener<List<Anime>>)
```

2024-07-26 04:10 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/AnimeDataSource.kt
> +        fun getAnimeTopRate(limit: Int, page: Int, listener: OnResultListener<MutableList<Anime>>)
```suggestion
        fun getAnimeNew(limit: Int, page: Int, listener: OnResultListener<List<Anime>>)
        fun getAnimeTopRate(limit: Int, page: Int, listener: OnResultListener<List<Anime>>)
```

2024-07-26 04:10 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/remote/AnimeRemoteDataSource.kt
> +
```suggestion
```

2024-07-26 04:10 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/remote/fetchjson/ParseJson.kt
> +            )
Dùng GSON cho gọn e

2024-07-26 04:10 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/remote/fetchjson/ParseJson.kt
> +            val jsonObject = jsonArray.getJSONObject(i)
GSON

2024-07-26 04:10 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/remote/fetchjson/ParseDataWithJson.kt
> +}
Đây là các hàm Utils, các hàm này không cần phải khai báo trong một **Class**, có thể khai báo **top-level**.
nếu em khai báo thành class rồi tạo instance -> mỗi khi dùng sẽ tạo ra 1 vùng nhớ -> tiêu tốn bộ nhớ không cần thiết

2024-07-26 04:52 UTC, gianghv-3456 requested changes

2024-07-26 04:52 UTC, gianghv-3456 commented on app/src/main/java/com/example/anidb/data/repository/source/remote/fetchjson/ParseJson.kt
> +    fun animeParseJson(jsonObject: JSONObject) = Anime().apply {
Using GSON instead

2024-07-26 06:04 UTC, gianghv-3456 approved these changes

2024-07-26 06:04 UTC, merged